changelog:
  exclude:
    authors:
      - github-actions
  categories:
    - title: Features
      labels:
        - "type: feature"
    - title: Bugs
      labels:
        - "type: bug"
    - title: Documentation
      labels:
        - "type: docs"
    - title: Chores
      labels:
        - "type: chore"
    - title: Other Changes
      labels:
        - "*"
