name: Create Linear Issue on Discussions

on:
  discussion:
    types: [created]

jobs:
  create-linear-issue-on-discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Create the Linear Issue
        id: createIssue
        uses: ctriolo/action-create-linear-issue@v0.5
        with:
          linear-api-key: ${{secrets.LINEAR_API_KEY}}
          linear-team-key: "TRI"
          linear-issue-title: ${{github.event.discussion.title}}
          linear-issue-description: ${{github.event.discussion.body}}
          linear-attachment-url: ${{github.event.discussion.html_url}}
          linear-attachment-title: ${{github.event.discussion.title}}