on:
  pull_request:
  issues:
name: Label PR with team
permissions:
  contents: read
  pull-requests: write
jobs:
  team-labeler:
    runs-on: ubuntu-latest
    steps:
    - id: label-the-PR
      uses: actions/labeler@v5
    - uses: JulienKode/team-labeler-action@v1.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"